name: azkagram
description: A new Flutter project.
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ">=2.21.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 
  markdown: ^5.0.0
  easy_isolate: ^1.3.0 
  iconsax: ^0.0.8 
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0
  zxing2: ^0.1.0
  image: ^3.2.0
  telegram_client: ^0.3.5
  simulate: ^0.0.7
  pull_to_refresh: ^2.0.0
  hidable: ^1.0.2
  fl_chart: ^0.36.2
  ffmpeg_cli: ^0.1.0
  flutter_markdown: ^0.6.10+2
  cross_file: ^0.3.3+1
  flutter_tts: ^3.4.0
  brainly: ^0.0.1
  flame: ^1.2.0
  translator: ^0.1.7
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
